#####################################################################
#
# INPUT_DIR: The directory where the input images are location
# OUTPUTDIR: The directory where the output images and plots should be stored
#
#####################################################################
INPUT_DIR = "./Cancerouscellsmears2/"
OUTPUT_DIR = "./output/"


#################################################
#
# COLOR_CHANNEL:
#
#################################################
COLOR_CHANNEL = "R"

######################################################################
#
# SALT_PEPPER_STRENGTH and GAUSS_NOISE_STRENGTH:
#
####################################3#################################
SALT_PEPPER_STRENGTH = 0.4
GAUSS_NOISE_STRENGTH = 0.1

#####################################################################
#
# LINEAR_MASK and MEDIAN_MASK:
#
#####################################################################
LINEAR_MASK = 9
LINEAR_WEIGHTS = [
  [0, 0, 0],
  [0, 1, 0],
  [0, 0, 0]
]

MEDIAN_MASK = 1
MEDIAN_WEIGHTS = [[1]]